'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1022
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
'Imports System.Web.Services
'Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.0.30319.1.
'
Namespace GetInvoiceDetail
    
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="GetInvoiceDetailBinding", [Namespace]:="http://xmlns.www.tigo.com/GetInvoiceDetail/V1"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ParameterType()))>  _
    Partial Public Class GetInvoiceDetailService
        'Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol
        Private GetInvoiceDetailOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.11.14.4:7004/osb/services/GetInvoiceDetail_2_0"
        End Sub
        
        '''<remarks/>
        Public Event GetInvoiceDetailCompleted As GetInvoiceDetailCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function GetInvoiceDetail(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/GetInvoiceDetailRequest/V1")> ByVal GetInvoiceDetailRequest As GetInvoiceDetailRequest) As <System.Xml.Serialization.XmlElementAttribute("GetInvoiceDetailResponse", [Namespace]:="http://xmlns.tigo.com/GetInvoiceDetailResponse/V1")> GetInvoiceDetailResponse
            Dim results() As Object = Me.Invoke("GetInvoiceDetail", New Object() {GetInvoiceDetailRequest})
            Return CType(results(0),GetInvoiceDetailResponse)
        End Function
        
        '''<remarks/>
        Public Function BeginGetInvoiceDetail(ByVal GetInvoiceDetailRequest As GetInvoiceDetailRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetInvoiceDetail", New Object() {GetInvoiceDetailRequest}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetInvoiceDetail(ByVal asyncResult As System.IAsyncResult) As GetInvoiceDetailResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),GetInvoiceDetailResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetInvoiceDetailAsync(ByVal GetInvoiceDetailRequest As GetInvoiceDetailRequest)
            Me.GetInvoiceDetailAsync(GetInvoiceDetailRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInvoiceDetailAsync(ByVal GetInvoiceDetailRequest As GetInvoiceDetailRequest, ByVal userState As Object)
            If (Me.GetInvoiceDetailOperationCompleted Is Nothing) Then
                Me.GetInvoiceDetailOperationCompleted = AddressOf Me.OnGetInvoiceDetailOperationCompleted
            End If
            Me.InvokeAsync("GetInvoiceDetail", New Object() {GetInvoiceDetailRequest}, Me.GetInvoiceDetailOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetInvoiceDetailOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetInvoiceDetailCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetInvoiceDetailCompleted(Me, New GetInvoiceDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetInvoiceDetailRequest/V1")>  _
    Partial Public Class GetInvoiceDetailRequest
        
        Private requestHeaderField As RequestHeader
        
        Private requestBodyField As GetInvoiceDetailRequestRequestBody
        
        Private additionalParametersField() As ParameterType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
        Public Property RequestHeader() As RequestHeader
            Get
                Return Me.requestHeaderField
            End Get
            Set
                Me.requestHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property requestBody() As GetInvoiceDetailRequestRequestBody
            Get
                Return Me.requestBodyField
            End Get
            Set
                Me.requestBodyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalParameters() As ParameterType()
            Get
                Return Me.additionalParametersField
            End Get
            Set
                Me.additionalParametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Partial Public Class RequestHeader
        
        Private generalConsumerInformationField As GeneralConsumerInfoType
        
        '''<remarks/>
        Public Property GeneralConsumerInformation() As GeneralConsumerInfoType
            Get
                Return Me.generalConsumerInformationField
            End Get
            Set
                Me.generalConsumerInformationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Partial Public Class GeneralConsumerInfoType
        
        Private consumerIDField As String
        
        Private transactionIDField As String
        
        Private countryField As CountryContentType
        
        Private correlationIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property consumerID() As String
            Get
                Return Me.consumerIDField
            End Get
            Set
                Me.consumerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property transactionID() As String
            Get
                Return Me.transactionIDField
            End Get
            Set
                Me.transactionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property country() As CountryContentType
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property correlationID() As String
            Get
                Return Me.correlationIDField
            End Get
            Set
                Me.correlationIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Public Enum CountryContentType
        
        '''<remarks/>
        SLV
        
        '''<remarks/>
        GTM
        
        '''<remarks/>
        HND
        
        '''<remarks/>
        BOL
        
        '''<remarks/>
        COL
        
        '''<remarks/>
        PRY
        
        '''<remarks/>
        TCD
        
        '''<remarks/>
        COD
        
        '''<remarks/>
        GHA
        
        '''<remarks/>
        MUS
        
        '''<remarks/>
        RWA
        
        '''<remarks/>
        SEN
        
        '''<remarks/>
        TZA
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/GetInvoiceDetailResponse/V1")>  _
    Partial Public Class invoiceDetailType
        
        Private acctCodeField As String
        
        Private acctIdField As String
        
        Private custCodeField As String
        
        Private custIdField As String
        
        Private msisdnField As String
        
        Private subIdField As String
        
        Private transTypeField As String
        
        Private invoiceIdField As String
        
        Private invoiceAmountField As String
        
        Private openAmountField As String
        
        Private invoiceNoField As String
        
        Private invoiceDateField As String
        
        Private dueDateField As String
        
        Private settleDateField As String
        
        Private reasonCodeField As String
        
        Private billCycleIdField As String
        
        Private currencyIdField As String
        
        Private additionalDataField() As ParameterType
        
        '''<remarks/>
        Public Property acctCode() As String
            Get
                Return Me.acctCodeField
            End Get
            Set
                Me.acctCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acctId() As String
            Get
                Return Me.acctIdField
            End Get
            Set
                Me.acctIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property custCode() As String
            Get
                Return Me.custCodeField
            End Get
            Set
                Me.custCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property custId() As String
            Get
                Return Me.custIdField
            End Get
            Set
                Me.custIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property msisdn() As String
            Get
                Return Me.msisdnField
            End Get
            Set
                Me.msisdnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property subId() As String
            Get
                Return Me.subIdField
            End Get
            Set
                Me.subIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property transType() As String
            Get
                Return Me.transTypeField
            End Get
            Set
                Me.transTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property invoiceId() As String
            Get
                Return Me.invoiceIdField
            End Get
            Set
                Me.invoiceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceAmount() As String
            Get
                Return Me.invoiceAmountField
            End Get
            Set(value As String)
                Me.invoiceAmountField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OpenAmount() As String
            Get
                Return Me.openAmountField
            End Get
            Set(value As String)
                Me.openAmountField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property invoiceNo() As String
            Get
                Return Me.invoiceNoField
            End Get
            Set
                Me.invoiceNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property invoiceDate() As String
            Get
                Return Me.invoiceDateField
            End Get
            Set
                Me.invoiceDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property dueDate() As String
            Get
                Return Me.dueDateField
            End Get
            Set
                Me.dueDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SettleDate() As String
            Get
                Return Me.settleDateField
            End Get
            Set
                Me.settleDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReasonCode() As String
            Get
                Return Me.reasonCodeField
            End Get
            Set
                Me.reasonCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillCycleId() As String
            Get
                Return Me.billCycleIdField
            End Get
            Set
                Me.billCycleIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property currencyId() As String
            Get
                Return Me.currencyIdField
            End Get
            Set
                Me.currencyIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalData() As ParameterType()
            Get
                Return Me.additionalDataField
            End Get
            Set
                Me.additionalDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ParameterType/V2")>  _
    Partial Public Class ParameterType
        
        Private parameterNameField As String
        
        Private parameterValueField As String
        
        '''<remarks/>
        Public Property parameterName() As String
            Get
                Return Me.parameterNameField
            End Get
            Set
                Me.parameterNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property parameterValue() As String
            Get
                Return Me.parameterValueField
            End Get
            Set
                Me.parameterValueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Partial Public Class GeneralResponseType
        
        Private correlationIDField As String
        
        Private statusField As System.Nullable(Of StatusContentType)
        
        Private statusFieldSpecified As Boolean
        
        Private codeField As String
        
        Private codeTypeField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property correlationID() As String
            Get
                Return Me.correlationIDField
            End Get
            Set
                Me.correlationIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As System.Nullable(Of StatusContentType)
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property codeType() As String
            Get
                Return Me.codeTypeField
            End Get
            Set
                Me.codeTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Public Enum StatusContentType
        
        '''<remarks/>
        [ERROR]
        
        '''<remarks/>
        OK
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetInvoiceDetailRequest/V1")>  _
    Partial Public Class GetInvoiceDetailRequestRequestBody
        
        Private itemField As String
        
        Private itemElementNameField As ItemChoiceType
        
        Private msisdnField As String
        
        Private transTypeField As String
        
        Private totalRowNumField As String
        
        Private beginRowNumField As String
        
        Private fetchRowNumField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("acctCode", GetType(String)),  _
         System.Xml.Serialization.XmlElementAttribute("acctId", GetType(String)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set
                Me.itemElementNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property msisdn() As String
            Get
                Return Me.msisdnField
            End Get
            Set
                Me.msisdnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property transType() As String
            Get
                Return Me.transTypeField
            End Get
            Set
                Me.transTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalRowNum() As String
            Get
                Return Me.totalRowNumField
            End Get
            Set(value As String)
                Me.totalRowNumField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BeginRowNum() As String
            Get
                Return Me.beginRowNumField
            End Get
            Set(value As String)
                Me.beginRowNumField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FetchRowNum() As String
            Get
                Return Me.fetchRowNumField
            End Get
            Set(value As String)
                Me.fetchRowNumField = Value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/GetInvoiceDetailRequest/V1", IncludeInSchema:=false)>  _
    Public Enum ItemChoiceType
        
        '''<remarks/>
        acctCode
        
        '''<remarks/>
        acctId
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetInvoiceDetailResponse/V1")>  _
    Partial Public Class GetInvoiceDetailResponse
        
        Private responseHeaderField As ResponseHeader
        
        Private responseBodyField As GetInvoiceDetailResponseResponseBody
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
        Public Property ResponseHeader() As ResponseHeader
            Get
                Return Me.responseHeaderField
            End Get
            Set
                Me.responseHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseBody() As GetInvoiceDetailResponseResponseBody
            Get
                Return Me.responseBodyField
            End Get
            Set
                Me.responseBodyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Partial Public Class ResponseHeader
        
        Private generalResponseField As GeneralResponseType
        
        '''<remarks/>
        Public Property GeneralResponse() As GeneralResponseType
            Get
                Return Me.generalResponseField
            End Get
            Set
                Me.generalResponseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetInvoiceDetailResponse/V1")>  _
    Partial Public Class GetInvoiceDetailResponseResponseBody
        
        Private invoiceDetailListField() As invoiceDetailType
        
        Private totalRowNumField As String
        
        Private beginRowNumField As String
        
        Private fetchRowNumField As String
        
        Private additionalResultField() As ParameterType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("invoiceDetail", IsNullable:=True)> _
        Public Property invoiceDetailList() As invoiceDetailType()
            Get
                Return Me.invoiceDetailListField
            End Get
            Set(value As invoiceDetailType())
                Me.invoiceDetailListField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalRowNum() As String
            Get
                Return Me.totalRowNumField
            End Get
            Set(value As String)
                Me.totalRowNumField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BeginRowNum() As String
            Get
                Return Me.beginRowNumField
            End Get
            Set(value As String)
                Me.beginRowNumField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FetchRowNum() As String
            Get
                Return Me.fetchRowNumField
            End Get
            Set(value As String)
                Me.fetchRowNumField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalResult() As ParameterType()
            Get
                Return Me.additionalResultField
            End Get
            Set
                Me.additionalResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")>  _
    Public Delegate Sub GetInvoiceDetailCompletedEventHandler(ByVal sender As Object, ByVal e As GetInvoiceDetailCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetInvoiceDetailCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetInvoiceDetailResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetInvoiceDetailResponse)
            End Get
        End Property
    End Class
End Namespace
