'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1022
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.0.30319.1.
'
Namespace GetSecurityDepositDetails
    
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="GetSecurityDepositDetailsBinding", [Namespace]:="http://xmlns.tigo.com/GetSecurityDepositDetails/V1"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ParameterType()))>  _
    Partial Public Class GetSecurityDepositDetailsService
        'Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol
        Private GetSecurityDepositDetailsOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.11.14.4:7004/osb/services/GetSecurityDepositDetails_1_0"
        End Sub
        
        '''<remarks/>
        Public Event GetSecurityDepositDetailsCompleted As GetSecurityDepositDetailsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function GetSecurityDepositDetails(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/GetSecurityDepositDetailsRequest/V1")> ByVal GetSecurityDepositDetailsRequest As GetSecurityDepositDetailsRequest) As <System.Xml.Serialization.XmlElementAttribute("GetSecurityDepositDetailsResponse", [Namespace]:="http://xmlns.tigo.com/GetSecurityDepositDetailsResponse/V1")> GetSecurityDepositDetailsResponse
            Dim results() As Object = Me.Invoke("GetSecurityDepositDetails", New Object() {GetSecurityDepositDetailsRequest})
            Return CType(results(0),GetSecurityDepositDetailsResponse)
        End Function
        
        '''<remarks/>
        Public Function BeginGetSecurityDepositDetails(ByVal GetSecurityDepositDetailsRequest As GetSecurityDepositDetailsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetSecurityDepositDetails", New Object() {GetSecurityDepositDetailsRequest}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetSecurityDepositDetails(ByVal asyncResult As System.IAsyncResult) As GetSecurityDepositDetailsResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),GetSecurityDepositDetailsResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSecurityDepositDetailsAsync(ByVal GetSecurityDepositDetailsRequest As GetSecurityDepositDetailsRequest)
            Me.GetSecurityDepositDetailsAsync(GetSecurityDepositDetailsRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSecurityDepositDetailsAsync(ByVal GetSecurityDepositDetailsRequest As GetSecurityDepositDetailsRequest, ByVal userState As Object)
            If (Me.GetSecurityDepositDetailsOperationCompleted Is Nothing) Then
                Me.GetSecurityDepositDetailsOperationCompleted = AddressOf Me.OnGetSecurityDepositDetailsOperationCompleted
            End If
            Me.InvokeAsync("GetSecurityDepositDetails", New Object() {GetSecurityDepositDetailsRequest}, Me.GetSecurityDepositDetailsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSecurityDepositDetailsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSecurityDepositDetailsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSecurityDepositDetailsCompleted(Me, New GetSecurityDepositDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetSecurityDepositDetailsRequest/V1")>  _
    Partial Public Class GetSecurityDepositDetailsRequest
        
        Private requestHeaderField As RequestHeader
        
        Private requestBodyField As GetSecurityDepositDetailsRequestRequestBody
        
        Private additionalParametersField() As ParameterType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
        Public Property RequestHeader() As RequestHeader
            Get
                Return Me.requestHeaderField
            End Get
            Set
                Me.requestHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property requestBody() As GetSecurityDepositDetailsRequestRequestBody
            Get
                Return Me.requestBodyField
            End Get
            Set
                Me.requestBodyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalParameters() As ParameterType()
            Get
                Return Me.additionalParametersField
            End Get
            Set
                Me.additionalParametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Partial Public Class RequestHeader
        
        Private generalConsumerInformationField As GeneralConsumerInfoType
        
        '''<remarks/>
        Public Property GeneralConsumerInformation() As GeneralConsumerInfoType
            Get
                Return Me.generalConsumerInformationField
            End Get
            Set
                Me.generalConsumerInformationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Partial Public Class GeneralConsumerInfoType
        
        Private consumerIDField As String
        
        Private transactionIDField As String
        
        Private countryField As CountryContentType
        
        Private correlationIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property consumerID() As String
            Get
                Return Me.consumerIDField
            End Get
            Set
                Me.consumerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property transactionID() As String
            Get
                Return Me.transactionIDField
            End Get
            Set
                Me.transactionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property country() As CountryContentType
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property correlationID() As String
            Get
                Return Me.correlationIDField
            End Get
            Set
                Me.correlationIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Public Enum CountryContentType
        
        '''<remarks/>
        SLV
        
        '''<remarks/>
        GTM
        
        '''<remarks/>
        HND
        
        '''<remarks/>
        BOL
        
        '''<remarks/>
        COL
        
        '''<remarks/>
        PRY
        
        '''<remarks/>
        TCD
        
        '''<remarks/>
        COD
        
        '''<remarks/>
        GHA
        
        '''<remarks/>
        MUS
        
        '''<remarks/>
        RWA
        
        '''<remarks/>
        SEN
        
        '''<remarks/>
        TZA
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Partial Public Class GeneralResponseType
        
        Private correlationIDField As String
        
        Private statusField As System.Nullable(Of StatusContentType)
        
        Private statusFieldSpecified As Boolean
        
        Private codeField As String
        
        Private codeTypeField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property correlationID() As String
            Get
                Return Me.correlationIDField
            End Get
            Set
                Me.correlationIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As System.Nullable(Of StatusContentType)
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property codeType() As String
            Get
                Return Me.codeTypeField
            End Get
            Set
                Me.codeTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Public Enum StatusContentType
        
        '''<remarks/>
        [ERROR]
        
        '''<remarks/>
        OK
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ParameterType/V2")>  _
    Partial Public Class ParameterType
        
        Private parameterNameField As String
        
        Private parameterValueField As String
        
        '''<remarks/>
        Public Property parameterName() As String
            Get
                Return Me.parameterNameField
            End Get
            Set
                Me.parameterNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property parameterValue() As String
            Get
                Return Me.parameterValueField
            End Get
            Set
                Me.parameterValueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetSecurityDepositDetailsRequest/V1")>  _
    Partial Public Class GetSecurityDepositDetailsRequestRequestBody
        
        Private invoiceIdField As String
        
        Private acctIdField As String
        
        Private depositTypeField As String
        
        Private paidFlagField As GetSecurityDepositDetailsRequestRequestBodyPaidFlag
        
        '''<remarks/>
        Public Property invoiceId() As String
            Get
                Return Me.invoiceIdField
            End Get
            Set
                Me.invoiceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acctId() As String
            Get
                Return Me.acctIdField
            End Get
            Set
                Me.acctIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property depositType() As String
            Get
                Return Me.depositTypeField
            End Get
            Set
                Me.depositTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property paidFlag() As GetSecurityDepositDetailsRequestRequestBodyPaidFlag
            Get
                Return Me.paidFlagField
            End Get
            Set
                Me.paidFlagField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetSecurityDepositDetailsRequest/V1")>  _
    Public Enum GetSecurityDepositDetailsRequestRequestBodyPaidFlag
        
        '''<remarks/>
        unpaid
        
        '''<remarks/>
        paid
        
        '''<remarks/>
        all
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetSecurityDepositDetailsResponse/V1")>  _
    Partial Public Class GetSecurityDepositDetailsResponse
        
        Private responseHeaderField As ResponseHeader
        
        Private responseBodyField As GetSecurityDepositDetailsResponseResponseBody
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
        Public Property ResponseHeader() As ResponseHeader
            Get
                Return Me.responseHeaderField
            End Get
            Set
                Me.responseHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseBody() As GetSecurityDepositDetailsResponseResponseBody
            Get
                Return Me.responseBodyField
            End Get
            Set
                Me.responseBodyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Partial Public Class ResponseHeader
        
        Private generalResponseField As GeneralResponseType
        
        '''<remarks/>
        Public Property GeneralResponse() As GeneralResponseType
            Get
                Return Me.generalResponseField
            End Get
            Set
                Me.generalResponseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetSecurityDepositDetailsResponse/V1")>  _
    Partial Public Class GetSecurityDepositDetailsResponseResponseBody
        
        Private depositDetailResultListField() As GetSecurityDepositDetailsResponseResponseBodyDepositDetailResultValue
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("DepositDetailResultValue", IsNullable:=false)>  _
        Public Property DepositDetailResultList() As GetSecurityDepositDetailsResponseResponseBodyDepositDetailResultValue()
            Get
                Return Me.depositDetailResultListField
            End Get
            Set
                Me.depositDetailResultListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetSecurityDepositDetailsResponse/V1")>  _
    Partial Public Class GetSecurityDepositDetailsResponseResponseBodyDepositDetailResultValue
        
        Private acctCodeField As String
        
        Private acctIdField As String
        
        Private msisdnField As String
        
        Private subIdField As String
        
        Private custCodeField As String
        
        Private custIdField As String
        
        Private depositTypeField As String
        
        Private invoiceAmountField As String
        
        Private openAmountField As String
        
        Private channelField As String
        
        Private waiveReasonField As String
        
        Private statusField As String
        
        Private entryDateField As String
        
        Private depPaymentListField() As GetSecurityDepositDetailsResponseResponseBodyDepositDetailResultValueDepPaymentValue
        
        '''<remarks/>
        Public Property AcctCode() As String
            Get
                Return Me.acctCodeField
            End Get
            Set
                Me.acctCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AcctId() As String
            Get
                Return Me.acctIdField
            End Get
            Set
                Me.acctIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Msisdn() As String
            Get
                Return Me.msisdnField
            End Get
            Set
                Me.msisdnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SubId() As String
            Get
                Return Me.subIdField
            End Get
            Set
                Me.subIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustCode() As String
            Get
                Return Me.custCodeField
            End Get
            Set
                Me.custCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustId() As String
            Get
                Return Me.custIdField
            End Get
            Set
                Me.custIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DepositType() As String
            Get
                Return Me.depositTypeField
            End Get
            Set
                Me.depositTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceAmount() As String
            Get
                Return Me.invoiceAmountField
            End Get
            Set
                Me.invoiceAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OpenAmount() As String
            Get
                Return Me.openAmountField
            End Get
            Set
                Me.openAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Channel() As String
            Get
                Return Me.channelField
            End Get
            Set
                Me.channelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WaiveReason() As String
            Get
                Return Me.waiveReasonField
            End Get
            Set
                Me.waiveReasonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EntryDate() As String
            Get
                Return Me.entryDateField
            End Get
            Set
                Me.entryDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("DepPaymentValue", IsNullable:=false)>  _
        Public Property DepPaymentList() As GetSecurityDepositDetailsResponseResponseBodyDepositDetailResultValueDepPaymentValue()
            Get
                Return Me.depPaymentListField
            End Get
            Set
                Me.depPaymentListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetSecurityDepositDetailsResponse/V1")>  _
    Partial Public Class GetSecurityDepositDetailsResponseResponseBodyDepositDetailResultValueDepPaymentValue
        
        Private paymentMethodField As String
        
        Private amountField As String
        
        '''<remarks/>
        Public Property PaymentMethod() As String
            Get
                Return Me.paymentMethodField
            End Get
            Set
                Me.paymentMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Amount() As String
            Get
                Return Me.amountField
            End Get
            Set(value As String)
                Me.amountField = Value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")>  _
    Public Delegate Sub GetSecurityDepositDetailsCompletedEventHandler(ByVal sender As Object, ByVal e As GetSecurityDepositDetailsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSecurityDepositDetailsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetSecurityDepositDetailsResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetSecurityDepositDetailsResponse)
            End Get
        End Property
    End Class
End Namespace
