'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.0.30319.1.
'
Namespace GetSubscriberInfo
    
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="GetSubscriberInfoBinding", [Namespace]:="http://xmlns.tigo.com/GetSubscriberInfo/V1"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AccountType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Product)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ParameterType()))>  _
    Partial Public Class GetSubscriberInfoService
        'Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol
        Private GetSubscriberInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.11.14.4:7004/osb/services/GetSubscriberInfo_1_0"
        End Sub
        
        '''<remarks/>
        Public Event GetSubscriberInfoCompleted As GetSubscriberInfoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function GetSubscriberInfo(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/GetSubscriberInfoRequest/V1")> ByVal GetSubscriberInfoRequest As GetSubscriberInfoRequest) As <System.Xml.Serialization.XmlElementAttribute("GetSubscriberInfoResponse", [Namespace]:="http://xmlns.tigo.com/GetSubscriberInfoResponse/V1")> GetSubscriberInfoResponse
            Dim results() As Object = Me.Invoke("GetSubscriberInfo", New Object() {GetSubscriberInfoRequest})
            Return CType(results(0),GetSubscriberInfoResponse)
        End Function
        
        '''<remarks/>
        Public Function BeginGetSubscriberInfo(ByVal GetSubscriberInfoRequest As GetSubscriberInfoRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetSubscriberInfo", New Object() {GetSubscriberInfoRequest}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetSubscriberInfo(ByVal asyncResult As System.IAsyncResult) As GetSubscriberInfoResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),GetSubscriberInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSubscriberInfoAsync(ByVal GetSubscriberInfoRequest As GetSubscriberInfoRequest)
            Me.GetSubscriberInfoAsync(GetSubscriberInfoRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSubscriberInfoAsync(ByVal GetSubscriberInfoRequest As GetSubscriberInfoRequest, ByVal userState As Object)
            If (Me.GetSubscriberInfoOperationCompleted Is Nothing) Then
                Me.GetSubscriberInfoOperationCompleted = AddressOf Me.OnGetSubscriberInfoOperationCompleted
            End If
            Me.InvokeAsync("GetSubscriberInfo", New Object() {GetSubscriberInfoRequest}, Me.GetSubscriberInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSubscriberInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSubscriberInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSubscriberInfoCompleted(Me, New GetSubscriberInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetSubscriberInfoRequest/V1")>  _
    Partial Public Class GetSubscriberInfoRequest
        
        Private requestHeaderField As RequestHeader
        
        Private requestBodyField As GetSubscriberInfoRequestRequestBody
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
        Public Property RequestHeader() As RequestHeader
            Get
                Return Me.requestHeaderField
            End Get
            Set
                Me.requestHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property requestBody() As GetSubscriberInfoRequestRequestBody
            Get
                Return Me.requestBodyField
            End Get
            Set
                Me.requestBodyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Partial Public Class RequestHeader
        
        Private generalConsumerInformationField As GeneralConsumerInfoType
        
        '''<remarks/>
        Public Property GeneralConsumerInformation() As GeneralConsumerInfoType
            Get
                Return Me.generalConsumerInformationField
            End Get
            Set
                Me.generalConsumerInformationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Partial Public Class GeneralConsumerInfoType
        
        Private consumerIDField As String
        
        Private transactionIDField As String
        
        Private countryField As CountryContentType
        
        Private correlationIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property consumerID() As String
            Get
                Return Me.consumerIDField
            End Get
            Set
                Me.consumerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property transactionID() As String
            Get
                Return Me.transactionIDField
            End Get
            Set
                Me.transactionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property country() As CountryContentType
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property correlationID() As String
            Get
                Return Me.correlationIDField
            End Get
            Set
                Me.correlationIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Public Enum CountryContentType
        
        '''<remarks/>
        SLV
        
        '''<remarks/>
        GTM
        
        '''<remarks/>
        HND
        
        '''<remarks/>
        BOL
        
        '''<remarks/>
        COL
        
        '''<remarks/>
        PRY
        
        '''<remarks/>
        TCD
        
        '''<remarks/>
        COD
        
        '''<remarks/>
        GHA
        
        '''<remarks/>
        MUS
        
        '''<remarks/>
        RWA
        
        '''<remarks/>
        SEN
        
        '''<remarks/>
        TZA
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(account)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/AccountType/V1")>  _
    Partial Public Class AccountType
        
        Private customerNameField As String
        
        Private codeField As String
        
        Private addressField As String
        
        Private titleField As String
        
        Private billcycleTypeField As System.Nullable(Of Integer)
        
        Private relationCustomerField As System.Nullable(Of Integer)
        
        Private relationCustomerFieldSpecified As Boolean
        
        Private parentAcctCodeField As String
        
        Private additionalPropertiesField() As ParameterType
        
        '''<remarks/>
        Public Property customerName() As String
            Get
                Return Me.customerNameField
            End Get
            Set
                Me.customerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property address() As String
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property billcycleType() As System.Nullable(Of Integer)
            Get
                Return Me.billcycleTypeField
            End Get
            Set
                Me.billcycleTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property relationCustomer() As System.Nullable(Of Integer)
            Get
                Return Me.relationCustomerField
            End Get
            Set
                Me.relationCustomerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property relationCustomerSpecified() As Boolean
            Get
                Return Me.relationCustomerFieldSpecified
            End Get
            Set
                Me.relationCustomerFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property parentAcctCode() As String
            Get
                Return Me.parentAcctCodeField
            End Get
            Set
                Me.parentAcctCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalProperties() As ParameterType()
            Get
                Return Me.additionalPropertiesField
            End Get
            Set
                Me.additionalPropertiesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ParameterType/V2")>  _
    Partial Public Class ParameterType
        
        Private parameterNameField As String
        
        Private parameterValueField As String
        
        '''<remarks/>
        Public Property parameterName() As String
            Get
                Return Me.parameterNameField
            End Get
            Set
                Me.parameterNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property parameterValue() As String
            Get
                Return Me.parameterValueField
            End Get
            Set
                Me.parameterValueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/GetSubscriberInfoResponse/V1")>  _
    Partial Public Class account
        Inherits AccountType
        
        Private subscriberNumberField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("subscriberNumber", IsNullable:=true)>  _
        Public Property subscriberNumber() As String()
            Get
                Return Me.subscriberNumberField
            End Get
            Set
                Me.subscriberNumberField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/SubscriberType/V1")>  _
    Partial Public Class Service
        
        Private serviceIdField As String
        
        Private statusField As String
        
        Private registrationTimeField As String
        
        Private additionalPropertiesField() As ParameterType
        
        '''<remarks/>
        Public Property serviceId() As String
            Get
                Return Me.serviceIdField
            End Get
            Set
                Me.serviceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property registrationTime() As String
            Get
                Return Me.registrationTimeField
            End Get
            Set
                Me.registrationTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalProperties() As ParameterType()
            Get
                Return Me.additionalPropertiesField
            End Get
            Set
                Me.additionalPropertiesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/SubscriberType/V1")>  _
    Partial Public Class BindSubscriberNo
        
        Private subscriberNoField As String
        
        Private subscriberNoTypeField As Integer
        
        Private imsiField As String
        
        Private applyTimeField As String
        
        Private expireTimeField As String
        
        '''<remarks/>
        Public Property subscriberNo() As String
            Get
                Return Me.subscriberNoField
            End Get
            Set
                Me.subscriberNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property subscriberNoType() As Integer
            Get
                Return Me.subscriberNoTypeField
            End Get
            Set
                Me.subscriberNoTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property imsi() As String
            Get
                Return Me.imsiField
            End Get
            Set
                Me.imsiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property applyTime() As String
            Get
                Return Me.applyTimeField
            End Get
            Set
                Me.applyTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property expireTime() As String
            Get
                Return Me.expireTimeField
            End Get
            Set
                Me.expireTimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(product)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/SubscriberType/V1")>  _
    Partial Public Class Product
        
        Private productIdField As String
        
        Private additionalPropertiesField() As ParameterType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property productId() As String
            Get
                Return Me.productIdField
            End Get
            Set
                Me.productIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalProperties() As ParameterType()
            Get
                Return Me.additionalPropertiesField
            End Get
            Set
                Me.additionalPropertiesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
    ' System.SerializableAttribute(),  _
    ' System.Diagnostics.DebuggerStepThroughAttribute(),  _
    ' System.ComponentModel.DesignerCategoryAttribute("code"),  _
    ' System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/GetSubscriberInfoResponse/V1")>  _
    Partial Public Class product
        'Inherits Product

        Private productOrderKeyField As String

        Private effectiveDateField As String

        Private expiredDateField As String

        Private statusField As String

        Private cycleStartTimeField As String

        Private cycleEndTimeField As String

        Private billStatusField As System.Nullable(Of Integer)

        Private billStatusFieldSpecified As Boolean

        Private bindSubscriberNoField() As BindSubscriberNo

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property productOrderKey() As String
            Get
                Return Me.productOrderKeyField
            End Get
            Set(value As String)
                Me.productOrderKeyField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property effectiveDate() As String
            Get
                Return Me.effectiveDateField
            End Get
            Set(value As String)
                Me.effectiveDateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property expiredDate() As String
            Get
                Return Me.expiredDateField
            End Get
            Set(value As String)
                Me.expiredDateField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set(value As String)
                Me.statusField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property cycleStartTime() As String
            Get
                Return Me.cycleStartTimeField
            End Get
            Set(value As String)
                Me.cycleStartTimeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property cycleEndTime() As String
            Get
                Return Me.cycleEndTimeField
            End Get
            Set(value As String)
                Me.cycleEndTimeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property billStatus() As System.Nullable(Of Integer)
            Get
                Return Me.billStatusField
            End Get
            Set(value As System.Nullable(Of Integer))
                Me.billStatusField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property billStatusSpecified() As Boolean
            Get
                Return Me.billStatusFieldSpecified
            End Get
            Set(value As Boolean)
                Me.billStatusFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("bindSubscriberNo")> _
        Public Property bindSubscriberNo() As BindSubscriberNo()
            Get
                Return Me.bindSubscriberNoField
            End Get
            Set(value As BindSubscriberNo())
                Me.bindSubscriberNoField = Value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/SubscriberType/V1")>  _
    Partial Public Class SubscriberType
        
        Private imsiField As String
        
        Private clientCodeField As String
        
        Private brandIdField As String
        
        Private languageField As lang
        
        Private smsLanguageField As lang
        
        Private smsLanguageFieldSpecified As Boolean
        
        Private ussdLanguageField As lang
        
        Private ussdLanguageFieldSpecified As Boolean
        
        Private customerTypeField As customerType
        
        Private initialCreditField As Integer
        
        Private initialCreditFieldSpecified As Boolean
        
        Private belToAreaIDField As String
        
        Private mainProductIDField As String
        
        Private additionalPropertiesField() As ParameterType
        
        '''<remarks/>
        Public Property imsi() As String
            Get
                Return Me.imsiField
            End Get
            Set
                Me.imsiField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property clientCode() As String
            Get
                Return Me.clientCodeField
            End Get
            Set
                Me.clientCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property brandId() As String
            Get
                Return Me.brandIdField
            End Get
            Set
                Me.brandIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property language() As lang
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property smsLanguage() As lang
            Get
                Return Me.smsLanguageField
            End Get
            Set
                Me.smsLanguageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property smsLanguageSpecified() As Boolean
            Get
                Return Me.smsLanguageFieldSpecified
            End Get
            Set
                Me.smsLanguageFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ussdLanguage() As lang
            Get
                Return Me.ussdLanguageField
            End Get
            Set
                Me.ussdLanguageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ussdLanguageSpecified() As Boolean
            Get
                Return Me.ussdLanguageFieldSpecified
            End Get
            Set
                Me.ussdLanguageFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property customerType() As customerType
            Get
                Return Me.customerTypeField
            End Get
            Set
                Me.customerTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property initialCredit() As Integer
            Get
                Return Me.initialCreditField
            End Get
            Set
                Me.initialCreditField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property initialCreditSpecified() As Boolean
            Get
                Return Me.initialCreditFieldSpecified
            End Get
            Set
                Me.initialCreditFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property belToAreaID() As String
            Get
                Return Me.belToAreaIDField
            End Get
            Set
                Me.belToAreaIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mainProductID() As String
            Get
                Return Me.mainProductIDField
            End Get
            Set
                Me.mainProductIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalProperties() As ParameterType()
            Get
                Return Me.additionalPropertiesField
            End Get
            Set
                Me.additionalPropertiesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/SubscriberType/V1")>  _
    Public Enum lang
        
        '''<remarks/>
        Swahili
        
        '''<remarks/>
        English
        
        '''<remarks/>
        French
        
        '''<remarks/>
        Wolof
        
        '''<remarks/>
        Lingala
        
        '''<remarks/>
        Kikongo
        
        '''<remarks/>
        Tshiluba
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/SubscriberType/V1")> _
    Public Enum customerType

        '''<remarks/>
        Prepaid

        '''<remarks/>
        Postpaid

        '''<remarks/>
        Hybrid
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/CustomerType/V1")> _
    Partial Public Class CustomerType1

        Private nameField As String

        Private clientCodeField As String

        Private firstNameField As String

        Private middleNameField As String

        Private lastNameField As String

        Private birthDateField As Date

        Private genderField As CustomerTypeGender

        Private maritalStatusField As CustomerTypeMaritalStatus

        Private maritalStatusFieldSpecified As Boolean

        Private addressField As String

        Private zipCodeField As String

        Private emailField As String

        Private nationalityField As String

        Private documentNumberField As String

        Private documentTypeField As System.Nullable(Of documentType)

        Private documentTypeFieldSpecified As Boolean

        Private documentExpeditionDateField As Date

        Private documentExpeditionDateFieldSpecified As Boolean

        Private belToAreaIDField As String

        Private clientGradeField As clientGrade

        Private clientTypeField As System.Nullable(Of clientType)

        Private clientTypeFieldSpecified As Boolean

        Private clientStateField As clientState

        Private clientStateFieldSpecified As Boolean

        Private economicActivityField As CustomerTypeEconomicActivity

        Private economicActivityFieldSpecified As Boolean

        Private socialNumberField As String

        Private admissionDateField As Date

        Private admissionDateFieldSpecified As Boolean

        Private segmentationField As String

        Private scoringField As scoringType

        Private scoringFieldSpecified As Boolean

        Private faxField As String

        Private rucField As String

        Private businessNameField As String

        Private baseCurrencyField As String

        Private guaranteesNumberField As String

        Private additionalPropertiesField() As ParameterType

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property clientCode() As String
            Get
                Return Me.clientCodeField
            End Get
            Set(value As String)
                Me.clientCodeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property firstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set(value As String)
                Me.firstNameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property middleName() As String
            Get
                Return Me.middleNameField
            End Get
            Set(value As String)
                Me.middleNameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property lastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set(value As String)
                Me.lastNameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property birthDate() As Date
            Get
                Return Me.birthDateField
            End Get
            Set(value As Date)
                Me.birthDateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property gender() As CustomerTypeGender
            Get
                Return Me.genderField
            End Get
            Set(value As CustomerTypeGender)
                Me.genderField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property maritalStatus() As CustomerTypeMaritalStatus
            Get
                Return Me.maritalStatusField
            End Get
            Set(value As CustomerTypeMaritalStatus)
                Me.maritalStatusField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property maritalStatusSpecified() As Boolean
            Get
                Return Me.maritalStatusFieldSpecified
            End Get
            Set(value As Boolean)
                Me.maritalStatusFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property address() As String
            Get
                Return Me.addressField
            End Get
            Set(value As String)
                Me.addressField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property zipCode() As String
            Get
                Return Me.zipCodeField
            End Get
            Set(value As String)
                Me.zipCodeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property email() As String
            Get
                Return Me.emailField
            End Get
            Set(value As String)
                Me.emailField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property nationality() As String
            Get
                Return Me.nationalityField
            End Get
            Set(value As String)
                Me.nationalityField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property documentNumber() As String
            Get
                Return Me.documentNumberField
            End Get
            Set(value As String)
                Me.documentNumberField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property documentType() As System.Nullable(Of documentType)
            Get
                Return Me.documentTypeField
            End Get
            Set(value As System.Nullable(Of documentType))
                Me.documentTypeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property documentTypeSpecified() As Boolean
            Get
                Return Me.documentTypeFieldSpecified
            End Get
            Set(value As Boolean)
                Me.documentTypeFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property documentExpeditionDate() As Date
            Get
                Return Me.documentExpeditionDateField
            End Get
            Set(value As Date)
                Me.documentExpeditionDateField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property documentExpeditionDateSpecified() As Boolean
            Get
                Return Me.documentExpeditionDateFieldSpecified
            End Get
            Set(value As Boolean)
                Me.documentExpeditionDateFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property belToAreaID() As String
            Get
                Return Me.belToAreaIDField
            End Get
            Set(value As String)
                Me.belToAreaIDField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property clientGrade() As clientGrade
            Get
                Return Me.clientGradeField
            End Get
            Set(value As clientGrade)
                Me.clientGradeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property clientType() As System.Nullable(Of clientType)
            Get
                Return Me.clientTypeField
            End Get
            Set(value As System.Nullable(Of clientType))
                Me.clientTypeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property clientTypeSpecified() As Boolean
            Get
                Return Me.clientTypeFieldSpecified
            End Get
            Set(value As Boolean)
                Me.clientTypeFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property clientState() As clientState
            Get
                Return Me.clientStateField
            End Get
            Set(value As clientState)
                Me.clientStateField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property clientStateSpecified() As Boolean
            Get
                Return Me.clientStateFieldSpecified
            End Get
            Set(value As Boolean)
                Me.clientStateFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property economicActivity() As CustomerTypeEconomicActivity
            Get
                Return Me.economicActivityField
            End Get
            Set(value As CustomerTypeEconomicActivity)
                Me.economicActivityField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property economicActivitySpecified() As Boolean
            Get
                Return Me.economicActivityFieldSpecified
            End Get
            Set(value As Boolean)
                Me.economicActivityFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property socialNumber() As String
            Get
                Return Me.socialNumberField
            End Get
            Set(value As String)
                Me.socialNumberField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property admissionDate() As Date
            Get
                Return Me.admissionDateField
            End Get
            Set(value As Date)
                Me.admissionDateField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property admissionDateSpecified() As Boolean
            Get
                Return Me.admissionDateFieldSpecified
            End Get
            Set(value As Boolean)
                Me.admissionDateFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property segmentation() As String
            Get
                Return Me.segmentationField
            End Get
            Set(value As String)
                Me.segmentationField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property scoring() As scoringType
            Get
                Return Me.scoringField
            End Get
            Set(value As scoringType)
                Me.scoringField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property scoringSpecified() As Boolean
            Get
                Return Me.scoringFieldSpecified
            End Get
            Set(value As Boolean)
                Me.scoringFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property fax() As String
            Get
                Return Me.faxField
            End Get
            Set(value As String)
                Me.faxField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ruc() As String
            Get
                Return Me.rucField
            End Get
            Set(value As String)
                Me.rucField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property businessName() As String
            Get
                Return Me.businessNameField
            End Get
            Set(value As String)
                Me.businessNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property baseCurrency() As String
            Get
                Return Me.baseCurrencyField
            End Get
            Set(value As String)
                Me.baseCurrencyField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property guaranteesNumber() As String
            Get
                Return Me.guaranteesNumberField
            End Get
            Set(value As String)
                Me.guaranteesNumberField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=False)> _
        Public Property additionalProperties() As ParameterType()
            Get
                Return Me.additionalPropertiesField
            End Get
            Set(value As ParameterType())
                Me.additionalPropertiesField = Value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/CustomerType/V1")>  _
    Public Enum CustomerTypeGender
        
        '''<remarks/>
        Male
        
        '''<remarks/>
        Female
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/CustomerType/V1")>  _
    Public Enum CustomerTypeMaritalStatus
        
        '''<remarks/>
        Unspecified
        
        '''<remarks/>
        [Single]
        
        '''<remarks/>
        Married
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/CustomerType/V1")>  _
    Public Enum documentType
        
        '''<remarks/>
        IDCard
        
        '''<remarks/>
        OfficerCard
        
        '''<remarks/>
        Passport
        
        '''<remarks/>
        DrivingLicense
        
        '''<remarks/>
        BusinessLicense
        
        '''<remarks/>
        Others
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/CustomerType/V1")>  _
    Public Enum clientGrade
        
        '''<remarks/>
        [Default]
        
        '''<remarks/>
        CustomerLevel1
        
        '''<remarks/>
        CustomerLevel2
        
        '''<remarks/>
        CustomerLevel3
        
        '''<remarks/>
        CustomerLevel4
        
        '''<remarks/>
        CustomerLevel5
        
        '''<remarks/>
        CustomerLevel6
        
        '''<remarks/>
        CustomerLevel7
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/CustomerType/V1")>  _
    Public Enum clientType
        
        '''<remarks/>
        Individual
        
        '''<remarks/>
        CUG
        
        '''<remarks/>
        Company
        
        '''<remarks/>
        Agent
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/CustomerType/V1")>  _
    Public Enum clientState
        
        '''<remarks/>
        Normal
        
        '''<remarks/>
        Abnormal
        
        '''<remarks/>
        Unspecified
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/CustomerType/V1")>  _
    Public Enum CustomerTypeEconomicActivity
        
        '''<remarks/>
        Unspecified
        
        '''<remarks/>
        Teacher
        
        '''<remarks/>
        Doctor
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/CustomerType/V1")>  _
    Public Enum scoringType
        
        '''<remarks/>
        SilverClass
        
        '''<remarks/>
        GoldClass
        
        '''<remarks/>
        Unspecific
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Partial Public Class GeneralResponseType
        
        Private correlationIDField As String
        
        Private statusField As System.Nullable(Of StatusContentType)
        
        Private statusFieldSpecified As Boolean
        
        Private codeField As String
        
        Private codeTypeField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property correlationID() As String
            Get
                Return Me.correlationIDField
            End Get
            Set
                Me.correlationIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As System.Nullable(Of StatusContentType)
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property codeType() As String
            Get
                Return Me.codeTypeField
            End Get
            Set
                Me.codeTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Public Enum StatusContentType
        
        '''<remarks/>
        [ERROR]
        
        '''<remarks/>
        OK
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetSubscriberInfoRequest/V1")>  _
    Partial Public Class GetSubscriberInfoRequestRequestBody
        
        Private msisdnField As String
        
        Private searchTypeField As searchType
        
        Private additionalParametersField() As ParameterType
        
        '''<remarks/>
        Public Property msisdn() As String
            Get
                Return Me.msisdnField
            End Get
            Set
                Me.msisdnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property searchType() As searchType
            Get
                Return Me.searchTypeField
            End Get
            Set
                Me.searchTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalParameters() As ParameterType()
            Get
                Return Me.additionalParametersField
            End Get
            Set
                Me.additionalParametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/GetSubscriberInfoRequest/V1")>  _
    Public Enum searchType
        
        '''<remarks/>
        CUSTOMER
        
        '''<remarks/>
        SUBSCRIBER
        
        '''<remarks/>
        ACCOUNT
        
        '''<remarks/>
        ALL
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetSubscriberInfoResponse/V1")>  _
    Partial Public Class GetSubscriberInfoResponse
        
        Private responseHeaderField As ResponseHeader
        
        Private responseBodyField As GetSubscriberInfoResponseResponseBody
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
        Public Property ResponseHeader() As ResponseHeader
            Get
                Return Me.responseHeaderField
            End Get
            Set
                Me.responseHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseBody() As GetSubscriberInfoResponseResponseBody
            Get
                Return Me.responseBodyField
            End Get
            Set
                Me.responseBodyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Partial Public Class ResponseHeader
        
        Private generalResponseField As GeneralResponseType
        
        '''<remarks/>
        Public Property GeneralResponse() As GeneralResponseType
            Get
                Return Me.generalResponseField
            End Get
            Set
                Me.generalResponseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/GetSubscriberInfoResponse/V1")>  _
    Partial Public Class GetSubscriberInfoResponseResponseBody
        
        Private msisdnField As String
        
        Private customerField As CustomerType
        
        Private subscriberField As SubscriberType
        
        Private productsField() As product
        
        Private servicesField() As Service
        
        Private accountsField() As account
        
        Private additionalResultField() As ParameterType
        
        '''<remarks/>
        Public Property msisdn() As String
            Get
                Return Me.msisdnField
            End Get
            Set
                Me.msisdnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property customer() As CustomerType
            Get
                Return Me.customerField
            End Get
            Set
                Me.customerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property subscriber() As SubscriberType
            Get
                Return Me.subscriberField
            End Get
            Set
                Me.subscriberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property products() As product()
            Get
                Return Me.productsField
            End Get
            Set
                Me.productsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("service", IsNullable:=false)>  _
        Public Property services() As Service()
            Get
                Return Me.servicesField
            End Get
            Set
                Me.servicesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property accounts() As account()
            Get
                Return Me.accountsField
            End Get
            Set
                Me.accountsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalResult() As ParameterType()
            Get
                Return Me.additionalResultField
            End Get
            Set
                Me.additionalResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")>  _
    Public Delegate Sub GetSubscriberInfoCompletedEventHandler(ByVal sender As Object, ByVal e As GetSubscriberInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSubscriberInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetSubscriberInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetSubscriberInfoResponse)
            End Get
        End Property
    End Class
End Namespace
