'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1022
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.0.30319.1.
'
Namespace ManageSecurityDeposit
    
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ManageSecurityDepositBinding", [Namespace]:="http://xmlns.tigo.com/Service/ManageSecurityDeposit/V1"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ParameterType()))>  _
    Partial Public Class ManageSecurityDeposit
        'Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol
        Private SecurityDepositOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RefundSecurityDepositOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.11.14.4:7004/osb/services/ManageSecurityDeposit_1_0"
        End Sub
        
        '''<remarks/>
        Public Event SecurityDepositCompleted As SecurityDepositCompletedEventHandler
        
        '''<remarks/>
        Public Event RefundSecurityDepositCompleted As RefundSecurityDepositCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function SecurityDeposit(<System.Xml.Serialization.XmlElementAttribute("SecurityDeposit", [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")> ByVal SecurityDeposit1 As SecurityDeposit) As <System.Xml.Serialization.XmlElementAttribute("SecurityDepositResponse", [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositResponse/V1")> SecurityDepositResponse
            Dim results() As Object = Me.Invoke("SecurityDeposit", New Object() {SecurityDeposit1})
            Return CType(results(0),SecurityDepositResponse)
        End Function
        
        '''<remarks/>
        Public Function BeginSecurityDeposit(ByVal SecurityDeposit1 As SecurityDeposit, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SecurityDeposit", New Object() {SecurityDeposit1}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSecurityDeposit(ByVal asyncResult As System.IAsyncResult) As SecurityDepositResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SecurityDepositResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SecurityDepositAsync(ByVal SecurityDeposit1 As SecurityDeposit)
            Me.SecurityDepositAsync(SecurityDeposit1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SecurityDepositAsync(ByVal SecurityDeposit1 As SecurityDeposit, ByVal userState As Object)
            If (Me.SecurityDepositOperationCompleted Is Nothing) Then
                Me.SecurityDepositOperationCompleted = AddressOf Me.OnSecurityDepositOperationCompleted
            End If
            Me.InvokeAsync("SecurityDeposit", New Object() {SecurityDeposit1}, Me.SecurityDepositOperationCompleted, userState)
        End Sub
        
        Private Sub OnSecurityDepositOperationCompleted(ByVal arg As Object)
            If (Not (Me.SecurityDepositCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SecurityDepositCompleted(Me, New SecurityDepositCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function RefundSecurityDeposit(<System.Xml.Serialization.XmlElementAttribute("RefundSecurityDeposit", [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")> ByVal RefundSecurityDeposit1 As RefundSecurityDeposit) As <System.Xml.Serialization.XmlElementAttribute("RefundSecurityDepositResponse", [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositResponse/V1")> RefundSecurityDepositResponse
            Dim results() As Object = Me.Invoke("RefundSecurityDeposit", New Object() {RefundSecurityDeposit1})
            Return CType(results(0),RefundSecurityDepositResponse)
        End Function
        
        '''<remarks/>
        Public Function BeginRefundSecurityDeposit(ByVal RefundSecurityDeposit1 As RefundSecurityDeposit, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RefundSecurityDeposit", New Object() {RefundSecurityDeposit1}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRefundSecurityDeposit(ByVal asyncResult As System.IAsyncResult) As RefundSecurityDepositResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),RefundSecurityDepositResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RefundSecurityDepositAsync(ByVal RefundSecurityDeposit1 As RefundSecurityDeposit)
            Me.RefundSecurityDepositAsync(RefundSecurityDeposit1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RefundSecurityDepositAsync(ByVal RefundSecurityDeposit1 As RefundSecurityDeposit, ByVal userState As Object)
            If (Me.RefundSecurityDepositOperationCompleted Is Nothing) Then
                Me.RefundSecurityDepositOperationCompleted = AddressOf Me.OnRefundSecurityDepositOperationCompleted
            End If
            Me.InvokeAsync("RefundSecurityDeposit", New Object() {RefundSecurityDeposit1}, Me.RefundSecurityDepositOperationCompleted, userState)
        End Sub
        
        Private Sub OnRefundSecurityDepositOperationCompleted(ByVal arg As Object)
            If (Not (Me.RefundSecurityDepositCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RefundSecurityDepositCompleted(Me, New RefundSecurityDepositCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Partial Public Class SecurityDeposit
        
        Private requestHeaderField As RequestHeader
        
        Private requestBodyField As SecurityDepositRequestBody
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
        Public Property RequestHeader() As RequestHeader
            Get
                Return Me.requestHeaderField
            End Get
            Set
                Me.requestHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequestBody() As SecurityDepositRequestBody
            Get
                Return Me.requestBodyField
            End Get
            Set
                Me.requestBodyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Partial Public Class RequestHeader
        
        Private generalConsumerInformationField As GeneralConsumerInfoType
        
        '''<remarks/>
        Public Property GeneralConsumerInformation() As GeneralConsumerInfoType
            Get
                Return Me.generalConsumerInformationField
            End Get
            Set
                Me.generalConsumerInformationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Partial Public Class GeneralConsumerInfoType
        
        Private consumerIDField As String
        
        Private transactionIDField As String
        
        Private countryField As CountryContentType
        
        Private correlationIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property consumerID() As String
            Get
                Return Me.consumerIDField
            End Get
            Set
                Me.consumerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property transactionID() As String
            Get
                Return Me.transactionIDField
            End Get
            Set
                Me.transactionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property country() As CountryContentType
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property correlationID() As String
            Get
                Return Me.correlationIDField
            End Get
            Set
                Me.correlationIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Public Enum CountryContentType
        
        '''<remarks/>
        SLV
        
        '''<remarks/>
        GTM
        
        '''<remarks/>
        HND
        
        '''<remarks/>
        BOL
        
        '''<remarks/>
        COL
        
        '''<remarks/>
        PRY
        
        '''<remarks/>
        TCD
        
        '''<remarks/>
        COD
        
        '''<remarks/>
        GHA
        
        '''<remarks/>
        MUS
        
        '''<remarks/>
        RWA
        
        '''<remarks/>
        SEN
        
        '''<remarks/>
        TZA
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/CoreData/V1")>  _
    Partial Public Class responseBodyType
        
        Private responseCodeField As String
        
        Private responseMessageField As String
        
        '''<remarks/>
        Public Property responseCode() As String
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseMessage() As String
            Get
                Return Me.responseMessageField
            End Get
            Set
                Me.responseMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Partial Public Class GeneralResponseType
        
        Private correlationIDField As String
        
        Private statusField As System.Nullable(Of StatusContentType)
        
        Private statusFieldSpecified As Boolean
        
        Private codeField As String
        
        Private codeTypeField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property correlationID() As String
            Get
                Return Me.correlationIDField
            End Get
            Set
                Me.correlationIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As System.Nullable(Of StatusContentType)
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property codeType() As String
            Get
                Return Me.codeTypeField
            End Get
            Set
                Me.codeTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Public Enum StatusContentType
        
        '''<remarks/>
        [ERROR]
        
        '''<remarks/>
        OK
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Partial Public Class paymentDetail
        
        Private paymentMethodField As paymentMethod
        
        Private paymentAmountField As Decimal
        
        Private chequeNumberField As String
        
        Private bankCodeField As String
        
        Private cardNumberField As String
        
        Private cardTypeField As String
        
        Private cardBatchNumberField As String
        
        Private approvalCodeField As String
        
        Private remarkField As String
        
        '''<remarks/>
        Public Property paymentMethod() As paymentMethod
            Get
                Return Me.paymentMethodField
            End Get
            Set
                Me.paymentMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property paymentAmount() As Decimal
            Get
                Return Me.paymentAmountField
            End Get
            Set
                Me.paymentAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property chequeNumber() As String
            Get
                Return Me.chequeNumberField
            End Get
            Set
                Me.chequeNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bankCode() As String
            Get
                Return Me.bankCodeField
            End Get
            Set
                Me.bankCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardNumber() As String
            Get
                Return Me.cardNumberField
            End Get
            Set
                Me.cardNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardType() As String
            Get
                Return Me.cardTypeField
            End Get
            Set
                Me.cardTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardBatchNumber() As String
            Get
                Return Me.cardBatchNumberField
            End Get
            Set
                Me.cardBatchNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property approvalCode() As String
            Get
                Return Me.approvalCodeField
            End Get
            Set
                Me.approvalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property remark() As String
            Get
                Return Me.remarkField
            End Get
            Set
                Me.remarkField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Public Enum paymentMethod
        
        '''<remarks/>
        Cash
        
        '''<remarks/>
        Cheque
        
        '''<remarks/>
        Card
        
        '''<remarks/>
        Others
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ParameterType/V2")>  _
    Partial Public Class ParameterType
        
        Private parameterNameField As String
        
        Private parameterValueField As String
        
        '''<remarks/>
        Public Property parameterName() As String
            Get
                Return Me.parameterNameField
            End Get
            Set
                Me.parameterNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property parameterValue() As String
            Get
                Return Me.parameterValueField
            End Get
            Set
                Me.parameterValueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Partial Public Class SecurityDepositRequestBody
        
        Private msisdnField As String
        
        Private accountNumberField As String
        
        Private paymentDetailField As paymentDetail
        
        Private chargeCustomerField As Boolean
        
        Private additionalParametersField As SecurityDepositRequestBodyAdditionalParameters
        
        Public Sub New()
            MyBase.New
            Me.chargeCustomerField = true
        End Sub
        
        '''<remarks/>
        Public Property msisdn() As String
            Get
                Return Me.msisdnField
            End Get
            Set
                Me.msisdnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property accountNumber() As String
            Get
                Return Me.accountNumberField
            End Get
            Set
                Me.accountNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property paymentDetail() As paymentDetail
            Get
                Return Me.paymentDetailField
            End Get
            Set
                Me.paymentDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.ComponentModel.DefaultValueAttribute(true)>  _
        Public Property chargeCustomer() As Boolean
            Get
                Return Me.chargeCustomerField
            End Get
            Set
                Me.chargeCustomerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property additionalParameters() As SecurityDepositRequestBodyAdditionalParameters
            Get
                Return Me.additionalParametersField
            End Get
            Set
                Me.additionalParametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Partial Public Class SecurityDepositRequestBodyAdditionalParameters
        
        Private parameterTypeField() As ParameterType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2")>  _
        Public Property ParameterType() As ParameterType()
            Get
                Return Me.parameterTypeField
            End Get
            Set
                Me.parameterTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositResponse/V1")>  _
    Partial Public Class SecurityDepositResponse
        
        Private responseHeaderField As ResponseHeader
        
        Private responseBodyField As SecurityDepositResponseResponseBody
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
        Public Property ResponseHeader() As ResponseHeader
            Get
                Return Me.responseHeaderField
            End Get
            Set
                Me.responseHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseBody() As SecurityDepositResponseResponseBody
            Get
                Return Me.responseBodyField
            End Get
            Set
                Me.responseBodyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Partial Public Class ResponseHeader
        
        Private generalResponseField As GeneralResponseType
        
        '''<remarks/>
        Public Property GeneralResponse() As GeneralResponseType
            Get
                Return Me.generalResponseField
            End Get
            Set
                Me.generalResponseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositResponse/V1")>  _
    Partial Public Class SecurityDepositResponseResponseBody
        
        Private transactionReferenceField As String
        
        Private depositAmountField As Decimal
        
        Private additionalResultField() As ParameterType
        
        '''<remarks/>
        Public Property transactionReference() As String
            Get
                Return Me.transactionReferenceField
            End Get
            Set
                Me.transactionReferenceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property depositAmount() As Decimal
            Get
                Return Me.depositAmountField
            End Get
            Set
                Me.depositAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalResult() As ParameterType()
            Get
                Return Me.additionalResultField
            End Get
            Set
                Me.additionalResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Partial Public Class RefundSecurityDeposit
        
        Private requestHeaderField As RequestHeader
        
        Private requestBodyField As RefundSecurityDepositRequestBody
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
        Public Property RequestHeader() As RequestHeader
            Get
                Return Me.requestHeaderField
            End Get
            Set
                Me.requestHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequestBody() As RefundSecurityDepositRequestBody
            Get
                Return Me.requestBodyField
            End Get
            Set
                Me.requestBodyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Partial Public Class RefundSecurityDepositRequestBody
        
        Private itemField As String
        
        Private itemElementNameField As ItemChoiceType
        
        Private isCustomerField As RefundSecurityDepositRequestBodyIsCustomer
        
        Private msisdnField As String
        
        Private subIdField As String
        
        Private custNameField As String
        
        Private refundTypeField As RefundSecurityDepositRequestBodyRefundType
        
        Private amountField As Long
        
        Private bankAcctTypeField As RefundSecurityDepositRequestBodyBankAcctType
        
        Private bankAcctTypeFieldSpecified As Boolean
        
        Private bankBranchNumberField As String
        
        Private bankAcctNoField As String
        
        Private contactPhoneField As String
        
        Private bsnoField As String
        
        Private transIdField As String
        
        Private reasonCodeField As RefundSecurityDepositRequestBodyReasonCode
        
        Private rejectReasonField As String
        
        Private remark1Field As String
        
        Private channelIdField As String
        
        Private channelTypeField As String
        
        Private originalBsnoField As String
        
        Private originalInvoiceDateField As String
        
        Private originalFeeDetailField() As RefundSecurityDepositRequestBodyOriginalFeeDetailValue
        
        Private holdDaysField As Long
        
        Private holdDaysFieldSpecified As Boolean
        
        Private settleFlagField As String
        
        Private additionalParametersField As RefundSecurityDepositRequestBodyAdditionalParameters
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("acctCode", GetType(String)),  _
         System.Xml.Serialization.XmlElementAttribute("acctId", GetType(String)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set
                Me.itemElementNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property isCustomer() As RefundSecurityDepositRequestBodyIsCustomer
            Get
                Return Me.isCustomerField
            End Get
            Set
                Me.isCustomerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property msisdn() As String
            Get
                Return Me.msisdnField
            End Get
            Set
                Me.msisdnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property subId() As String
            Get
                Return Me.subIdField
            End Get
            Set
                Me.subIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property custName() As String
            Get
                Return Me.custNameField
            End Get
            Set
                Me.custNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property refundType() As RefundSecurityDepositRequestBodyRefundType
            Get
                Return Me.refundTypeField
            End Get
            Set
                Me.refundTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property amount() As Long
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bankAcctType() As RefundSecurityDepositRequestBodyBankAcctType
            Get
                Return Me.bankAcctTypeField
            End Get
            Set
                Me.bankAcctTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property bankAcctTypeSpecified() As Boolean
            Get
                Return Me.bankAcctTypeFieldSpecified
            End Get
            Set
                Me.bankAcctTypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bankBranchNumber() As String
            Get
                Return Me.bankBranchNumberField
            End Get
            Set
                Me.bankBranchNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bankAcctNo() As String
            Get
                Return Me.bankAcctNoField
            End Get
            Set
                Me.bankAcctNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property contactPhone() As String
            Get
                Return Me.contactPhoneField
            End Get
            Set
                Me.contactPhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bsno() As String
            Get
                Return Me.bsnoField
            End Get
            Set
                Me.bsnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property transId() As String
            Get
                Return Me.transIdField
            End Get
            Set
                Me.transIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property reasonCode() As RefundSecurityDepositRequestBodyReasonCode
            Get
                Return Me.reasonCodeField
            End Get
            Set
                Me.reasonCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rejectReason() As String
            Get
                Return Me.rejectReasonField
            End Get
            Set
                Me.rejectReasonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property remark1() As String
            Get
                Return Me.remark1Field
            End Get
            Set
                Me.remark1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property channelId() As String
            Get
                Return Me.channelIdField
            End Get
            Set
                Me.channelIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property channelType() As String
            Get
                Return Me.channelTypeField
            End Get
            Set
                Me.channelTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property originalBsno() As String
            Get
                Return Me.originalBsnoField
            End Get
            Set
                Me.originalBsnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property originalInvoiceDate() As String
            Get
                Return Me.originalInvoiceDateField
            End Get
            Set
                Me.originalInvoiceDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("originalFeeDetailValue", IsNullable:=false)>  _
        Public Property originalFeeDetail() As RefundSecurityDepositRequestBodyOriginalFeeDetailValue()
            Get
                Return Me.originalFeeDetailField
            End Get
            Set
                Me.originalFeeDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property holdDays() As Long
            Get
                Return Me.holdDaysField
            End Get
            Set
                Me.holdDaysField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property holdDaysSpecified() As Boolean
            Get
                Return Me.holdDaysFieldSpecified
            End Get
            Set
                Me.holdDaysFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property settleFlag() As String
            Get
                Return Me.settleFlagField
            End Get
            Set
                Me.settleFlagField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property additionalParameters() As RefundSecurityDepositRequestBodyAdditionalParameters
            Get
                Return Me.additionalParametersField
            End Get
            Set
                Me.additionalParametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1", IncludeInSchema:=false)>  _
    Public Enum ItemChoiceType
        
        '''<remarks/>
        acctCode
        
        '''<remarks/>
        acctId
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Public Enum RefundSecurityDepositRequestBodyIsCustomer
        
        '''<remarks/>
        Yes
        
        '''<remarks/>
        No
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Public Enum RefundSecurityDepositRequestBodyRefundType
        
        '''<remarks/>
        DirectDebit
        
        '''<remarks/>
        CreditCard
        
        '''<remarks/>
        Cash
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Public Enum RefundSecurityDepositRequestBodyBankAcctType
        
        '''<remarks/>
        Other
        
        '''<remarks/>
        Savings
        
        '''<remarks/>
        Transmission
        
        '''<remarks/>
        Current
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Public Enum RefundSecurityDepositRequestBodyReasonCode
        
        '''<remarks/>
        Suspension
        
        '''<remarks/>
        Overpayment
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Deposit waived")>  _
        Depositwaived
        
        '''<remarks/>
        Others
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Partial Public Class RefundSecurityDepositRequestBodyOriginalFeeDetailValue
        
        Private amountField As Long
        
        Private amountFieldSpecified As Boolean
        
        Private feeItemCodeField As String
        
        Private taxInclusiveField As RefundSecurityDepositRequestBodyOriginalFeeDetailValueTaxInclusive
        
        Private taxInclusiveFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property amount() As Long
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property amountSpecified() As Boolean
            Get
                Return Me.amountFieldSpecified
            End Get
            Set
                Me.amountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property feeItemCode() As String
            Get
                Return Me.feeItemCodeField
            End Get
            Set
                Me.feeItemCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property taxInclusive() As RefundSecurityDepositRequestBodyOriginalFeeDetailValueTaxInclusive
            Get
                Return Me.taxInclusiveField
            End Get
            Set
                Me.taxInclusiveField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property taxInclusiveSpecified() As Boolean
            Get
                Return Me.taxInclusiveFieldSpecified
            End Get
            Set
                Me.taxInclusiveFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Public Enum RefundSecurityDepositRequestBodyOriginalFeeDetailValueTaxInclusive
        
        '''<remarks/>
        Yes
        
        '''<remarks/>
        No
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositRequest/V1")>  _
    Partial Public Class RefundSecurityDepositRequestBodyAdditionalParameters
        
        Private parameterTypeField() As ParameterType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2")>  _
        Public Property ParameterType() As ParameterType()
            Get
                Return Me.parameterTypeField
            End Get
            Set
                Me.parameterTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ManageSecurityDepositResponse/V1")>  _
    Partial Public Class RefundSecurityDepositResponse
        
        Private responseHeaderField As ResponseHeader
        
        Private responseBodyField As responseBodyType
        
        Private additionalResultField() As ParameterType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
        Public Property ResponseHeader() As ResponseHeader
            Get
                Return Me.responseHeaderField
            End Get
            Set
                Me.responseHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseBody() As responseBodyType
            Get
                Return Me.responseBodyField
            End Get
            Set
                Me.responseBodyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalResult() As ParameterType()
            Get
                Return Me.additionalResultField
            End Get
            Set
                Me.additionalResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")>  _
    Public Delegate Sub SecurityDepositCompletedEventHandler(ByVal sender As Object, ByVal e As SecurityDepositCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SecurityDepositCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SecurityDepositResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SecurityDepositResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")>  _
    Public Delegate Sub RefundSecurityDepositCompletedEventHandler(ByVal sender As Object, ByVal e As RefundSecurityDepositCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RefundSecurityDepositCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RefundSecurityDepositResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RefundSecurityDepositResponse)
            End Get
        End Property
    End Class
End Namespace
