'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.0.30319.1.
'
Namespace RegisterPayment
    
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="RegisterPaymentBinding", [Namespace]:="http://xmlns.tigo.com/Service/RegisterPayment/V1"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ParameterType()))>  _
    Partial Public Class RegisterPaymentService
        'Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol
        Private RegisterPaymentOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.11.14.4:7004/osb/services/RegisterPayment_1_1"
        End Sub
        
        '''<remarks/>
        Public Event RegisterPaymentCompleted As RegisterPaymentCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function RegisterPayment(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/RegisterPaymentRequest/V1")> ByVal RegisterPaymentRequest As RegisterPaymentRequest) As <System.Xml.Serialization.XmlElementAttribute("RegisterPaymentResponse", [Namespace]:="http://xmlns.tigo.com/RegisterPaymentResponse/V1")> RegisterPaymentResponse
            Dim results() As Object = Me.Invoke("RegisterPayment", New Object() {RegisterPaymentRequest})
            Return CType(results(0),RegisterPaymentResponse)
        End Function
        
        '''<remarks/>
        Public Function BeginRegisterPayment(ByVal RegisterPaymentRequest As RegisterPaymentRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RegisterPayment", New Object() {RegisterPaymentRequest}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRegisterPayment(ByVal asyncResult As System.IAsyncResult) As RegisterPaymentResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),RegisterPaymentResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegisterPaymentAsync(ByVal RegisterPaymentRequest As RegisterPaymentRequest)
            Me.RegisterPaymentAsync(RegisterPaymentRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegisterPaymentAsync(ByVal RegisterPaymentRequest As RegisterPaymentRequest, ByVal userState As Object)
            If (Me.RegisterPaymentOperationCompleted Is Nothing) Then
                Me.RegisterPaymentOperationCompleted = AddressOf Me.OnRegisterPaymentOperationCompleted
            End If
            Me.InvokeAsync("RegisterPayment", New Object() {RegisterPaymentRequest}, Me.RegisterPaymentOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegisterPaymentOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegisterPaymentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegisterPaymentCompleted(Me, New RegisterPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/RegisterPaymentRequest/V1")>  _
    Partial Public Class RegisterPaymentRequest
        
        Private requestHeaderField As RequestHeader
        
        Private requestBodyField As requestBodyType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
        Public Property RequestHeader() As RequestHeader
            Get
                Return Me.requestHeaderField
            End Get
            Set
                Me.requestHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequestBody() As requestBodyType
            Get
                Return Me.requestBodyField
            End Get
            Set
                Me.requestBodyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Partial Public Class RequestHeader
        
        Private generalConsumerInformationField As GeneralConsumerInfoType
        
        '''<remarks/>
        Public Property GeneralConsumerInformation() As GeneralConsumerInfoType
            Get
                Return Me.generalConsumerInformationField
            End Get
            Set
                Me.generalConsumerInformationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Partial Public Class GeneralConsumerInfoType
        
        Private consumerIDField As String
        
        Private transactionIDField As String
        
        Private countryField As CountryContentType
        
        Private correlationIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property consumerID() As String
            Get
                Return Me.consumerIDField
            End Get
            Set
                Me.consumerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property transactionID() As String
            Get
                Return Me.transactionIDField
            End Get
            Set
                Me.transactionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property country() As CountryContentType
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property correlationID() As String
            Get
                Return Me.correlationIDField
            End Get
            Set
                Me.correlationIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RequestHeader/V3")>  _
    Public Enum CountryContentType
        
        '''<remarks/>
        SLV
        
        '''<remarks/>
        GTM
        
        '''<remarks/>
        HND
        
        '''<remarks/>
        BOL
        
        '''<remarks/>
        COL
        
        '''<remarks/>
        PRY
        
        '''<remarks/>
        TCD
        
        '''<remarks/>
        COD
        
        '''<remarks/>
        GHA
        
        '''<remarks/>
        MUS
        
        '''<remarks/>
        RWA
        
        '''<remarks/>
        SEN
        
        '''<remarks/>
        TZA
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RegisterPaymentResponse/V1")>  _
    Partial Public Class responseBodyType
        
        Private resultField As Boolean
        
        Private authorizationNumberField As String
        
        Private descriptionField As String
        
        Private additionalResultsField() As ParameterType
        
        '''<remarks/>
        Public Property result() As Boolean
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property authorizationNumber() As String
            Get
                Return Me.authorizationNumberField
            End Get
            Set
                Me.authorizationNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalResults() As ParameterType()
            Get
                Return Me.additionalResultsField
            End Get
            Set
                Me.additionalResultsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ParameterType/V2")>  _
    Partial Public Class ParameterType
        
        Private parameterNameField As String
        
        Private parameterValueField As String
        
        '''<remarks/>
        Public Property parameterName() As String
            Get
                Return Me.parameterNameField
            End Get
            Set
                Me.parameterNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property parameterValue() As String
            Get
                Return Me.parameterValueField
            End Get
            Set
                Me.parameterValueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Partial Public Class GeneralResponseType
        
        Private correlationIDField As String
        
        Private statusField As System.Nullable(Of StatusContentType)
        
        Private statusFieldSpecified As Boolean
        
        Private codeField As String
        
        Private codeTypeField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property correlationID() As String
            Get
                Return Me.correlationIDField
            End Get
            Set
                Me.correlationIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As System.Nullable(Of StatusContentType)
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property codeType() As String
            Get
                Return Me.codeTypeField
            End Get
            Set
                Me.codeTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Public Enum StatusContentType
        
        '''<remarks/>
        [ERROR]
        
        '''<remarks/>
        OK
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RegisterPaymentRequest/V1")>  _
    Partial Public Class paymentDetailType
        
        Private paymentMethodField As String
        
        Private amountField As Decimal
        
        Private chequeNumberField As String
        
        Private bankCodeField As String
        
        Private cardNumberField As String
        
        Private cardTypeField As String
        
        Private cardBatchNumberField As String
        
        Private approvalCodeField As String
        
        Private bankAcctNumberField As String
        
        Private voucherNumberField As String
        
        Private remarkField As String
        
        '''<remarks/>
        Public Property paymentMethod() As String
            Get
                Return Me.paymentMethodField
            End Get
            Set
                Me.paymentMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property amount() As Decimal
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property chequeNumber() As String
            Get
                Return Me.chequeNumberField
            End Get
            Set
                Me.chequeNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bankCode() As String
            Get
                Return Me.bankCodeField
            End Get
            Set
                Me.bankCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardNumber() As String
            Get
                Return Me.cardNumberField
            End Get
            Set
                Me.cardNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardType() As String
            Get
                Return Me.cardTypeField
            End Get
            Set
                Me.cardTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardBatchNumber() As String
            Get
                Return Me.cardBatchNumberField
            End Get
            Set
                Me.cardBatchNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property approvalCode() As String
            Get
                Return Me.approvalCodeField
            End Get
            Set
                Me.approvalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bankAcctNumber() As String
            Get
                Return Me.bankAcctNumberField
            End Get
            Set
                Me.bankAcctNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property voucherNumber() As String
            Get
                Return Me.voucherNumberField
            End Get
            Set
                Me.voucherNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property remark() As String
            Get
                Return Me.remarkField
            End Get
            Set
                Me.remarkField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.tigo.com/RegisterPaymentRequest/V1")>  _
    Partial Public Class requestBodyType
        
        Private invoiceNumberField As String
        
        Private invoiceTypeField As String
        
        Private invoiceSerialField As String
        
        Private msisdnField As String
        
        Private paymentReferenceField As String
        
        Private institutionIdField As String
        
        Private paymentDetailField As paymentDetailType
        
        Private additionalParametersField() As ParameterType
        
        '''<remarks/>
        Public Property invoiceNumber() As String
            Get
                Return Me.invoiceNumberField
            End Get
            Set
                Me.invoiceNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property invoiceType() As String
            Get
                Return Me.invoiceTypeField
            End Get
            Set
                Me.invoiceTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property invoiceSerial() As String
            Get
                Return Me.invoiceSerialField
            End Get
            Set
                Me.invoiceSerialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property msisdn() As String
            Get
                Return Me.msisdnField
            End Get
            Set
                Me.msisdnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property paymentReference() As String
            Get
                Return Me.paymentReferenceField
            End Get
            Set
                Me.paymentReferenceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property institutionId() As String
            Get
                Return Me.institutionIdField
            End Get
            Set
                Me.institutionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property paymentDetail() As paymentDetailType
            Get
                Return Me.paymentDetailField
            End Get
            Set
                Me.paymentDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ParameterType", [Namespace]:="http://xmlns.tigo.com/ParameterType/V2", IsNullable:=false)>  _
        Public Property additionalParameters() As ParameterType()
            Get
                Return Me.additionalParametersField
            End Get
            Set
                Me.additionalParametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/RegisterPaymentResponse/V1")>  _
    Partial Public Class RegisterPaymentResponse
        
        Private responseHeaderField As ResponseHeader
        
        Private responseBodyField As responseBodyType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
        Public Property ResponseHeader() As ResponseHeader
            Get
                Return Me.responseHeaderField
            End Get
            Set
                Me.responseHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseBody() As responseBodyType
            Get
                Return Me.responseBodyField
            End Get
            Set
                Me.responseBodyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://xmlns.tigo.com/ResponseHeader/V3")>  _
    Partial Public Class ResponseHeader
        
        Private generalResponseField As GeneralResponseType
        
        '''<remarks/>
        Public Property GeneralResponse() As GeneralResponseType
            Get
                Return Me.generalResponseField
            End Get
            Set
                Me.generalResponseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")>  _
    Public Delegate Sub RegisterPaymentCompletedEventHandler(ByVal sender As Object, ByVal e As RegisterPaymentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegisterPaymentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RegisterPaymentResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RegisterPaymentResponse)
            End Get
        End Property
    End Class
End Namespace
